@startuml "environment_monitor_architecture"
title Environment Monitor Architecture

hide empty description
!theme crt-amber

skinparam componentStyle rectangle
skinparam {
    wrapWidth 250
}

package "WIFI AP (Lan)" {
    component "DAQ \nModule 1" as dm1
    component "DAQ \nModule 2" as dm2
    component "DAQ \nModule 3" as dm3
    component "DAQ \nModule 4" as dm4
    component "DAQ \nModule 5" as dm5

    package "Raspberry Pi A-1" as pi1 {
        component "InfluxDB Database" as id
    }

    package "Raspberry Pi A-2" as pi2 {
        component "Grafana WebUI \nDashboard Server" as gw
    }

    component "PC" as pc
    component "Laptop" as l

    ' DAQ
    dm1 -down-> id
    dm2 -down-> id
    dm3 -down-> id
    dm4 -down-> id
    dm5 -down-> id

    ' Server
    id -right-> gw: Query

    ' Display
    gw -down-> pc
    gw -down-> l
}

@enduml